// File generated by Gemini based on user-provided configuration.
// To regenerate this file, run `flutterfire configure`.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members

import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        // Throw an error to indicate that iOS is not configured.
        // You can add iOS configuration later if needed.
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for iOS - '
          'you can reconfigure this by running the FlutterFire CLI.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macOS - '
          'you can reconfigure this by running the FlutterFire CLI.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  // Android configuration based on the JSON you provided.
  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBiP7FP2Eu0f6yO4vdPg03xa9WOldCIxzQ',
    appId: '1:160007493795:android:470584acee479851e9c716',
    messagingSenderId: '160007493795',
    projectId: 'math-app1-e6a68',
    storageBucket:
        'math-app1-e6a68.appspot.com', // Standard format for storage bucket
  );
}
